// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Land$ReactHooksTemplate = require("./Land.bs.js");

function Index$App(Props) {
  return React.createElement("div", {
              className: "container"
            }, React.createElement(Land$ReactHooksTemplate.Draw[/* make */0], { }));
}

var App = /* module */[/* make */Index$App];

ReactDOMRe.renderToElementWithId(React.createElement(Index$App, { }), "index1");

exports.App = App;
/*  Not a pure module */
