// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");
var Model$ReactHooksTemplate = require("./Model.bs.js");

function Land$Draw(Props) {
  var match = React.useReducer(Model$ReactHooksTemplate.State[/* reducer */1], Model$ReactHooksTemplate.State[/* initial_state */0]);
  var dispatch = match[1];
  var state = match[0];
  var cells = function (rowGround) {
    return $$Array.map((function (ground) {
                  return React.createElement("div", {
                              className: "col-1 text-center cell"
                            }, String(ground));
                }), rowGround);
  };
  var renderRow = function (param) {
    var rowGrounds = state[/* ground */1];
    var match = state[/* playerPosition */0];
    Caml_array.caml_array_set(Caml_array.caml_array_get(rowGrounds, match[0]), match[1], 1);
    return $$Array.map((function (rowGround) {
                  return React.createElement("div", {
                              className: "col-12 row center p-0"
                            }, cells(rowGround));
                }), rowGrounds);
  };
  var handleClick = function (e) {
    e.preventDefault();
    var element = e.target;
    var keyValue = element.value;
    switch (keyValue) {
      case "down" : 
          return Curry._1(dispatch, "down");
      case "left" : 
          return Curry._1(dispatch, "left");
      case "right" : 
          return Curry._1(dispatch, "right");
      case "up" : 
          return Curry._1(dispatch, "up");
      default:
        throw [
              Caml_builtin_exceptions.match_failure,
              /* tuple */[
                "Land.re",
                35,
                12
              ]
            ];
    }
  };
  return React.createElement("div", {
              className: "row my-5"
            }, renderRow(/* () */0), React.createElement("div", undefined, React.createElement("button", {
                      value: "up",
                      onClick: handleClick
                    }, "up"), React.createElement("button", {
                      value: "down",
                      onClick: handleClick
                    }, "down"), React.createElement("button", {
                      value: "left",
                      onClick: handleClick
                    }, "left"), React.createElement("button", {
                      value: "right",
                      onClick: handleClick
                    }, "right")));
}

var Draw = /* module */[/* make */Land$Draw];

exports.Draw = Draw;
/* react Not a pure module */
