// Generated by BUCKLESCRIPT VERSION 5.0.4, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var Player = /* module */[];

var Board = /* module */[];

var Car = /* module */[];

var initial_state_000 = /* playerPosition : tuple */[
  0,
  0
];

var initial_state_001 = /* ground */$$Array.make_matrix(15, 9, 0);

var initial_state = /* record */[
  initial_state_000,
  initial_state_001
];

function reducer(state, action) {
  var match = state[/* playerPosition */0];
  var x = match[1];
  var y = match[0];
  console.log(/* tuple */[
        y,
        x
      ]);
  switch (action) {
    case "down" : 
        Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* ground */1], y), x, 0);
        return /* record */[
                /* playerPosition : tuple */[
                  y + 1 | 0,
                  x
                ],
                /* ground */state[/* ground */1]
              ];
    case "left" : 
        Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* ground */1], y), x, 0);
        return /* record */[
                /* playerPosition : tuple */[
                  y,
                  x - 1 | 0
                ],
                /* ground */state[/* ground */1]
              ];
    case "right" : 
        Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* ground */1], y), x, 0);
        return /* record */[
                /* playerPosition : tuple */[
                  y,
                  x + 1 | 0
                ],
                /* ground */state[/* ground */1]
              ];
    case "up" : 
        Caml_array.caml_array_set(Caml_array.caml_array_get(state[/* ground */1], y), x, 0);
        return /* record */[
                /* playerPosition : tuple */[
                  y - 1 | 0,
                  x
                ],
                /* ground */state[/* ground */1]
              ];
    default:
      throw [
            Caml_builtin_exceptions.match_failure,
            /* tuple */[
              "Model.re",
              34,
              24
            ]
          ];
  }
}

var State = /* module */[
  /* initial_state */initial_state,
  /* reducer */reducer
];

exports.Player = Player;
exports.Board = Board;
exports.Car = Car;
exports.State = State;
/* initial_state Not a pure module */
